# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.alert_severity import AlertSeverity

class TestAlertSeverity(unittest.TestCase):
    """AlertSeverity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertSeverity(self):
        """Test AlertSeverity"""
        # inst = AlertSeverity()

if __name__ == '__main__':
    unittest.main()
