# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.metar_phenomenon import MetarPhenomenon

class TestMetarPhenomenon(unittest.TestCase):
    """MetarPhenomenon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetarPhenomenon:
        """Test MetarPhenomenon
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetarPhenomenon`
        """
        model = MetarPhenomenon()
        if include_optional:
            return MetarPhenomenon(
                intensity = 'light',
                modifier = 'patches',
                weather = 'fog_mist',
                raw_string = '',
                in_vicinity = True
            )
        else:
            return MetarPhenomenon(
                intensity = 'light',
                modifier = 'patches',
                weather = 'fog_mist',
                raw_string = '',
        )
        """

    def testMetarPhenomenon(self):
        """Test MetarPhenomenon"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
