# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.state_territory_code import StateTerritoryCode

class TestStateTerritoryCode(unittest.TestCase):
    """StateTerritoryCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStateTerritoryCode(self):
        """Test StateTerritoryCode"""
        # inst = StateTerritoryCode()

if __name__ == '__main__':
    unittest.main()
