# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.observation_station_collection_geo_json_all_of_features import ObservationStationCollectionGeoJsonAllOfFeatures

class TestObservationStationCollectionGeoJsonAllOfFeatures(unittest.TestCase):
    """ObservationStationCollectionGeoJsonAllOfFeatures unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ObservationStationCollectionGeoJsonAllOfFeatures:
        """Test ObservationStationCollectionGeoJsonAllOfFeatures
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ObservationStationCollectionGeoJsonAllOfFeatures`
        """
        model = ObservationStationCollectionGeoJsonAllOfFeatures()
        if include_optional:
            return ObservationStationCollectionGeoJsonAllOfFeatures(
                properties = pynwsdata.models.observation_station.ObservationStation(
                    @context = null, 
                    geometry = '', 
                    @id = '', 
                    @type = 'wx:ObservationStation', 
                    elevation = pynwsdata.models.quantitative_value.QuantitativeValue(
                        value = 1.337, 
                        max_value = 1.337, 
                        min_value = 1.337, 
                        unit_code = 'nwsUnit:R,rZ#UM/?R,Fp^l6$ARjbhJk C>i H'qT\\{<?'es#)#iK.YM{Rag2/!KB!k@5oXh.:', 
                        quality_control = 'Z', ), 
                    station_identifier = '', 
                    name = '', 
                    time_zone = '', 
                    forecast = '', 
                    county = '', 
                    fire_weather_zone = '', )
            )
        else:
            return ObservationStationCollectionGeoJsonAllOfFeatures(
        )
        """

    def testObservationStationCollectionGeoJsonAllOfFeatures(self):
        """Test ObservationStationCollectionGeoJsonAllOfFeatures"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
