# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.nws_center_weather_service_unit_id import NWSCenterWeatherServiceUnitId

class TestNWSCenterWeatherServiceUnitId(unittest.TestCase):
    """NWSCenterWeatherServiceUnitId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNWSCenterWeatherServiceUnitId(self):
        """Test NWSCenterWeatherServiceUnitId"""
        # inst = NWSCenterWeatherServiceUnitId()

if __name__ == '__main__':
    unittest.main()
