# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.zone_forecast_periods_inner import ZoneForecastPeriodsInner

class TestZoneForecastPeriodsInner(unittest.TestCase):
    """ZoneForecastPeriodsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ZoneForecastPeriodsInner:
        """Test ZoneForecastPeriodsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ZoneForecastPeriodsInner`
        """
        model = ZoneForecastPeriodsInner()
        if include_optional:
            return ZoneForecastPeriodsInner(
                number = 56,
                name = 'This Afternoon',
                detailed_forecast = ''
            )
        else:
            return ZoneForecastPeriodsInner(
                number = 56,
                name = 'This Afternoon',
                detailed_forecast = '',
        )
        """

    def testZoneForecastPeriodsInner(self):
        """Test ZoneForecastPeriodsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
