# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.icons_summary200_response_icons_value import IconsSummary200ResponseIconsValue

class TestIconsSummary200ResponseIconsValue(unittest.TestCase):
    """IconsSummary200ResponseIconsValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IconsSummary200ResponseIconsValue:
        """Test IconsSummary200ResponseIconsValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IconsSummary200ResponseIconsValue`
        """
        model = IconsSummary200ResponseIconsValue()
        if include_optional:
            return IconsSummary200ResponseIconsValue(
                description = ''
            )
        else:
            return IconsSummary200ResponseIconsValue(
                description = '',
        )
        """

    def testIconsSummary200ResponseIconsValue(self):
        """Test IconsSummary200ResponseIconsValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
