# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.alerts_active_count200_response import AlertsActiveCount200Response

class TestAlertsActiveCount200Response(unittest.TestCase):
    """AlertsActiveCount200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AlertsActiveCount200Response:
        """Test AlertsActiveCount200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AlertsActiveCount200Response`
        """
        model = AlertsActiveCount200Response()
        if include_optional:
            return AlertsActiveCount200Response(
                total = 0,
                land = 0,
                marine = 0,
                regions = {
                    'key' : 1
                    },
                areas = {
                    'key' : 1
                    },
                zones = {
                    'key' : 1
                    }
            )
        else:
            return AlertsActiveCount200Response(
        )
        """

    def testAlertsActiveCount200Response(self):
        """Test AlertsActiveCount200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
