# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.gridpoint_forecast_units import GridpointForecastUnits

class TestGridpointForecastUnits(unittest.TestCase):
    """GridpointForecastUnits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGridpointForecastUnits(self):
        """Test GridpointForecastUnits"""
        # inst = GridpointForecastUnits()

if __name__ == '__main__':
    unittest.main()
