# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.text_product_type_collection import TextProductTypeCollection

class TestTextProductTypeCollection(unittest.TestCase):
    """TextProductTypeCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TextProductTypeCollection:
        """Test TextProductTypeCollection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TextProductTypeCollection`
        """
        model = TextProductTypeCollection()
        if include_optional:
            return TextProductTypeCollection(
                context = None,
                graph = [
                    pynwsdata.models.text_product_type_collection__graph_inner.TextProductTypeCollection__graph_inner(
                        product_code = '', 
                        product_name = '', )
                    ]
            )
        else:
            return TextProductTypeCollection(
        )
        """

    def testTextProductTypeCollection(self):
        """Test TextProductTypeCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
