# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.glossary200_response import Glossary200Response

class TestGlossary200Response(unittest.TestCase):
    """Glossary200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Glossary200Response:
        """Test Glossary200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Glossary200Response`
        """
        model = Glossary200Response()
        if include_optional:
            return Glossary200Response(
                context = None,
                glossary = [
                    pynwsdata.models.glossary_200_response_glossary_inner.glossary_200_response_glossary_inner(
                        term = '', 
                        definition = '', )
                    ]
            )
        else:
            return Glossary200Response(
        )
        """

    def testGlossary200Response(self):
        """Test Glossary200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
