# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.alert_certainty import AlertCertainty

class TestAlertCertainty(unittest.TestCase):
    """AlertCertainty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertCertainty(self):
        """Test AlertCertainty"""
        # inst = AlertCertainty()

if __name__ == '__main__':
    unittest.main()
