# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.icons_size_parameter import IconsSizeParameter

class TestIconsSizeParameter(unittest.TestCase):
    """IconsSizeParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IconsSizeParameter:
        """Test IconsSizeParameter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IconsSizeParameter`
        """
        model = IconsSizeParameter()
        if include_optional:
            return IconsSizeParameter(
            )
        else:
            return IconsSizeParameter(
        )
        """

    def testIconsSizeParameter(self):
        """Test IconsSizeParameter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
