# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.nws_zone_type import NWSZoneType

class TestNWSZoneType(unittest.TestCase):
    """NWSZoneType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNWSZoneType(self):
        """Test NWSZoneType"""
        # inst = NWSZoneType()

if __name__ == '__main__':
    unittest.main()
