# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.geo_json_multi_line_string import GeoJSONMultiLineString

class TestGeoJSONMultiLineString(unittest.TestCase):
    """GeoJSONMultiLineString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeoJSONMultiLineString:
        """Test GeoJSONMultiLineString
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeoJSONMultiLineString`
        """
        model = GeoJSONMultiLineString()
        if include_optional:
            return GeoJSONMultiLineString(
                type = 'MultiLineString',
                coordinates = [
                    [
                        [
                            1.337
                            ]
                        ]
                    ],
                bbox = [
                    1.337
                    ]
            )
        else:
            return GeoJSONMultiLineString(
                type = 'MultiLineString',
                coordinates = [
                    [
                        [
                            1.337
                            ]
                        ]
                    ],
        )
        """

    def testGeoJSONMultiLineString(self):
        """Test GeoJSONMultiLineString"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
