# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.icons_summary200_response import IconsSummary200Response

class TestIconsSummary200Response(unittest.TestCase):
    """IconsSummary200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IconsSummary200Response:
        """Test IconsSummary200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IconsSummary200Response`
        """
        model = IconsSummary200Response()
        if include_optional:
            return IconsSummary200Response(
                context = None,
                icons = {
                    'key' : pynwsdata.models.icons_summary_200_response_icons_value.icons_summary_200_response_icons_value(
                        description = '', )
                    }
            )
        else:
            return IconsSummary200Response(
                icons = {
                    'key' : pynwsdata.models.icons_summary_200_response_icons_value.icons_summary_200_response_icons_value(
                        description = '', )
                    },
        )
        """

    def testIconsSummary200Response(self):
        """Test IconsSummary200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
