# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.alert_status import AlertStatus

class TestAlertStatus(unittest.TestCase):
    """AlertStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertStatus(self):
        """Test AlertStatus"""
        # inst = AlertStatus()

if __name__ == '__main__':
    unittest.main()
