# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.land_region_code import LandRegionCode

class TestLandRegionCode(unittest.TestCase):
    """LandRegionCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLandRegionCode(self):
        """Test LandRegionCode"""
        # inst = LandRegionCode()

if __name__ == '__main__':
    unittest.main()
