# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.alert_message_type import AlertMessageType

class TestAlertMessageType(unittest.TestCase):
    """AlertMessageType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertMessageType(self):
        """Test AlertMessageType"""
        # inst = AlertMessageType()

if __name__ == '__main__':
    unittest.main()
