# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.office import Office

class TestOffice(unittest.TestCase):
    """Office unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Office:
        """Test Office
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Office`
        """
        model = Office()
        if include_optional:
            return Office(
                context = None,
                type = 'GovernmentOrganization',
                id = '',
                id = '',
                name = '',
                address = pynwsdata.models.office_address.Office_address(
                    @type = 'PostalAddress', 
                    street_address = '', 
                    address_locality = '', 
                    address_region = '', 
                    postal_code = '', ),
                telephone = '',
                fax_number = '',
                email = '',
                same_as = '',
                nws_region = '',
                parent_organization = '',
                responsible_counties = [
                    ''
                    ],
                responsible_forecast_zones = [
                    ''
                    ],
                responsible_fire_zones = [
                    ''
                    ],
                approved_observation_stations = [
                    ''
                    ]
            )
        else:
            return Office(
        )
        """

    def testOffice(self):
        """Test Office"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
