# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynwsdata.models.metar_sky_coverage import MetarSkyCoverage

class TestMetarSkyCoverage(unittest.TestCase):
    """MetarSkyCoverage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetarSkyCoverage(self):
        """Test MetarSkyCoverage"""
        # inst = MetarSkyCoverage()

if __name__ == '__main__':
    unittest.main()
