# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class NWSCenterWeatherServiceUnitId(str, Enum):
    """
    Three-letter identifier for a Center Weather Service Unit (CWSU).
    """

    """
    allowed enum values
    """
    ZAB = 'ZAB'
    ZAN = 'ZAN'
    ZAU = 'ZAU'
    ZBW = 'ZBW'
    ZDC = 'ZDC'
    ZDV = 'ZDV'
    ZFA = 'ZFA'
    ZFW = 'ZFW'
    ZHU = 'ZHU'
    ZID = 'ZID'
    ZJX = 'ZJX'
    ZKC = 'ZKC'
    ZLA = 'ZLA'
    ZLC = 'ZLC'
    ZMA = 'ZMA'
    ZME = 'ZME'
    ZMP = 'ZMP'
    ZNY = 'ZNY'
    ZOA = 'ZOA'
    ZOB = 'ZOB'
    ZSE = 'ZSE'
    ZTL = 'ZTL'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NWSCenterWeatherServiceUnitId from a JSON string"""
        return cls(json.loads(json_str))


