# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AlertUrgency(str, Enum):
    """
    AlertUrgency
    """

    """
    allowed enum values
    """
    IMMEDIATE = 'Immediate'
    EXPECTED = 'Expected'
    FUTURE = 'Future'
    PAST = 'Past'
    UNKNOWN = 'Unknown'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AlertUrgency from a JSON string"""
        return cls(json.loads(json_str))


