# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from pynwsdata.models.geo_json_line_string import GeoJSONLineString
from pynwsdata.models.geo_json_multi_line_string import GeoJSONMultiLineString
from pynwsdata.models.geo_json_multi_point import GeoJSONMultiPoint
from pynwsdata.models.geo_json_multi_polygon import GeoJSONMultiPolygon
from pynwsdata.models.geo_json_point import GeoJSONPoint
from pynwsdata.models.geo_json_polygon import GeoJSONPolygon
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

GEOJSONGEOMETRY_ONE_OF_SCHEMAS = ["GeoJSONLineString", "GeoJSONMultiLineString", "GeoJSONMultiPoint", "GeoJSONMultiPolygon", "GeoJSONPoint", "GeoJSONPolygon"]

class GeoJsonGeometry(BaseModel):
    """
    A GeoJSON geometry object. Please refer to IETF RFC 7946 for information on the GeoJSON format.
    """
    # data type: GeoJSONPoint
    oneof_schema_1_validator: Optional[GeoJSONPoint] = None
    # data type: GeoJSONLineString
    oneof_schema_2_validator: Optional[GeoJSONLineString] = None
    # data type: GeoJSONPolygon
    oneof_schema_3_validator: Optional[GeoJSONPolygon] = None
    # data type: GeoJSONMultiPoint
    oneof_schema_4_validator: Optional[GeoJSONMultiPoint] = None
    # data type: GeoJSONMultiLineString
    oneof_schema_5_validator: Optional[GeoJSONMultiLineString] = None
    # data type: GeoJSONMultiPolygon
    oneof_schema_6_validator: Optional[GeoJSONMultiPolygon] = None
    actual_instance: Optional[Union[GeoJSONLineString, GeoJSONMultiLineString, GeoJSONMultiPoint, GeoJSONMultiPolygon, GeoJSONPoint, GeoJSONPolygon]] = None
    one_of_schemas: Set[str] = { "GeoJSONLineString", "GeoJSONMultiLineString", "GeoJSONMultiPoint", "GeoJSONMultiPolygon", "GeoJSONPoint", "GeoJSONPolygon" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        if v is None:
            return v

        instance = GeoJsonGeometry.model_construct()
        error_messages = []
        match = 0
        # validate data type: GeoJSONPoint
        if not isinstance(v, GeoJSONPoint):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GeoJSONPoint`")
        else:
            match += 1
        # validate data type: GeoJSONLineString
        if not isinstance(v, GeoJSONLineString):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GeoJSONLineString`")
        else:
            match += 1
        # validate data type: GeoJSONPolygon
        if not isinstance(v, GeoJSONPolygon):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GeoJSONPolygon`")
        else:
            match += 1
        # validate data type: GeoJSONMultiPoint
        if not isinstance(v, GeoJSONMultiPoint):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GeoJSONMultiPoint`")
        else:
            match += 1
        # validate data type: GeoJSONMultiLineString
        if not isinstance(v, GeoJSONMultiLineString):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GeoJSONMultiLineString`")
        else:
            match += 1
        # validate data type: GeoJSONMultiPolygon
        if not isinstance(v, GeoJSONMultiPolygon):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GeoJSONMultiPolygon`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in GeoJsonGeometry with oneOf schemas: GeoJSONLineString, GeoJSONMultiLineString, GeoJSONMultiPoint, GeoJSONMultiPolygon, GeoJSONPoint, GeoJSONPolygon. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in GeoJsonGeometry with oneOf schemas: GeoJSONLineString, GeoJSONMultiLineString, GeoJSONMultiPoint, GeoJSONMultiPolygon, GeoJSONPoint, GeoJSONPolygon. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: Optional[str]) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        if json_str is None:
            return instance

        error_messages = []
        match = 0

        # deserialize data into GeoJSONPoint
        try:
            instance.actual_instance = GeoJSONPoint.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GeoJSONLineString
        try:
            instance.actual_instance = GeoJSONLineString.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GeoJSONPolygon
        try:
            instance.actual_instance = GeoJSONPolygon.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GeoJSONMultiPoint
        try:
            instance.actual_instance = GeoJSONMultiPoint.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GeoJSONMultiLineString
        try:
            instance.actual_instance = GeoJSONMultiLineString.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GeoJSONMultiPolygon
        try:
            instance.actual_instance = GeoJSONMultiPolygon.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into GeoJsonGeometry with oneOf schemas: GeoJSONLineString, GeoJSONMultiLineString, GeoJSONMultiPoint, GeoJSONMultiPolygon, GeoJSONPoint, GeoJSONPolygon. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into GeoJsonGeometry with oneOf schemas: GeoJSONLineString, GeoJSONMultiLineString, GeoJSONMultiPoint, GeoJSONMultiPolygon, GeoJSONPoint, GeoJSONPolygon. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], GeoJSONLineString, GeoJSONMultiLineString, GeoJSONMultiPoint, GeoJSONMultiPolygon, GeoJSONPoint, GeoJSONPolygon]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


