# coding: utf-8

"""
    weather.gov API

    weather.gov API

    The version of the OpenAPI document: 1.13.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MarineRegionCode(str, Enum):
    """
    Marine region code. These are groups of marine areas combined. * AL: Alaska waters (PK) * AT: Atlantic Ocean (AM, AN) * GL: Great Lakes (LC, LE, LH, LM, LO, LS, SL) * GM: Gulf of Mexico (GM) * PA: Eastern Pacific Ocean and U.S. West Coast (PZ) * PI: Central and Western Pacific (PH, PM, PS) 
    """

    """
    allowed enum values
    """
    AL = 'AL'
    AT = 'AT'
    GL = 'GL'
    GM = 'GM'
    PA = 'PA'
    PI = 'PI'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MarineRegionCode from a JSON string"""
        return cls(json.loads(json_str))


